### ISSUE TITLE
Oldest OTP version that hex_core needs to support?

### ISSUE THREAD

**Issue by tomas-abrahamsson** [hexpm/hex_core#134]
Back in [Nov 2020](https://github.com/hexpm/hex_core/pull/105#issuecomment-720137496), hex_core needed to support OTP 17:

> hex_core needs to support OTP 17. This is because it needs to be usable by Hex which in turns needs to be usable by Elixir 1.0.x. At some point Hex will no longer support old Elixir versions but not quite yet.

I'm wondering what the oldest OTP version is that hex_core needs to support now? The background for my question is that for gpb, I've retained compatibility with older Erlang versions, but would like to know if I can drop some? For example for maps, Erlang 18 added support for using variables as map keys, so still needing to supporting Erlang 17 in gpb would impose some limitations on how the code could be phrased. As far as I'm aware, hex_core is the project that needs support for the oldest Erlang for gpb. A recent issue in gpb, tomas-abrahamsson/gpb#217 prompted this question.

I tried looking for info on the oldest Elixir still supported by Hex, but failed to find it. Related: the latest Elixir, currently 1.13.4, [says](https://hexdocs.pm/elixir/1.13.4/compatibility-and-deprecations.html) that the oldest Elixir to still receive security patches is 1.9, which is compatible with Erlang versions 20-22. Some more research: Debian old-stable, currently buster, ships Elixir 1.7.4 ([link](https://packages.debian.org/buster/elixir)), which is compatible with Erlang 19-22.

**Comment by wojtekmach** [comment]
Thank you for opening up this issue. The next major release, Hex 2.0, will support Elixir 1.5 [1] which is compatible with OTP 18.

hex_core is vendoring generated files [2] and thusly so does Hex and rebar3 and we're happy to continue using the current version. If there are performance improvements only available on certain OTP versions we'd definitely consider bumping up the requirement then. hex_core should definitely not hold back the development of gpb. Thank you for thinking about us though! :)

[1] https://github.com/hexpm/hex/pull/943
[2] https://github.com/hexpm/hex_core/blob/c0d33f8e9da18946ebf88d5d6f80f02339c65a04/src/hex_pb_names.erl
