### ISSUE TITLE
Invalid link to `http_api.md` in HexDocs

### ISSUE THREAD

**Issue by dimitarvp** [hexpm/hex_core#135]
The link https://github.com/hexpm/specifications/blob/master/http_api.md is correct on GitHub's `README.md` but the same link, when put here -- https://hexdocs.pm/hex_core/0.8.4/readme.html#api -- has a trailing dot added to it, leading to a 404.

**Comment by wojtekmach** [comment]
Fixed by bumping ExDoc version, thanks for the report.
