### ISSUE TITLE
Default tarball_max_size used by rebar3_hex too small

### ISSUE THREAD

**Issue by onno-vos-dev** [hexpm/hex_core#136]
When trying to publish docs for [aws-beam/aws-erlang](https://github.com/aws-beam/aws-erlang) I ran into an issue where trying to publish the docs resulted in the following error: `"tarball error, unknown POSIX error"`.

After patching OTP to include the actual error as per [my local OTP patch](https://github.com/onno-vos-dev/otp/blob/be6673e46e3046f7108238ebe3a0fa3b52ccf21f/lib/stdlib/src/erl_posix_msg.erl#L175) I figured the actual error is `too_big` which comes from https://github.com/hexpm/hex_core/blob/887160170cb9771eb706b0095a0a09afeac729f5/src/hex_tarball.erl#L143

`rebar3_hex` uses `hex_tarball:create_docs/1` and does not allow overriding the default configs coming from: https://github.com/hexpm/hex_core/blob/887160170cb9771eb706b0095a0a09afeac729f5/src/hex_tarball.erl#L114

One can argue for one of two things:
1. `rebar3_hex` should not use `create_docs/1` but should instead use `create_docs/2` and allow the overriding of `tarball_max_size` and `tarball_max_uncompressed_size`. 
2. The defaults chosen in `hex_core` are too small and hence should be increased.

**Comment by ericmj** [comment]
What size is the tarball you want to publish?

**Comment by onno-vos-dev** [comment]
> What size is the tarball you want to publish?

TarballSize: 8_615_229
UncompressedSize: 47_671_296

So with the new defaults, it'd work just fine as aws-erlang is just barely over the default limit that is currently in place.

**Comment by onno-vos-dev** [comment]
Someone mentioned that hexdocs does not allow tarballs bigger than 10MiB is that correct? In that case, I can adjust the PR to be of that size instead.
