### ISSUE TITLE
The spec for retirement_reason / retirement_params may be incorrect.

### ISSUE THREAD

**Issue by starbelly** [hexpm/hex_core#149]
The retirement reason / params is specified as as atoms and the keys for params as atoms. However, this does not work. iirc, at one point in time atoms were allowed, but that changed, and we can see that here : https://github.com/hexpm/hexpm/blob/e1251217d56ec91cdb104a27d9dd70eb08aa0f47/lib/hexpm_web/erlang_format.ex#L18

It may be there was intention to serialize atoms to strings from the client side via protobuf, but that doesn't appear to work. Testing locally nets me an http 400. 

I'm remember all this being discussed some years ago, but the memory is fuzzy around the details now. In other words, either this is a bug in encoding within hex_code (it does not fail in hex_core to be clear) or the specs need to be adjusted to reflect reality.

**Comment by paulo-ferraz-oliveira** [comment]
I'll propose a fix pr. If we end up understanding this as a spec-bug it's possible the pr gets accepted/merged.

**Comment by wojtekmach** [comment]
@starbelly @paulo-ferraz-oliveira this is the same issue as https://github.com/hexpm/hex_core/issues/71 i.e. we should standardise on binary keys? Regarding backwards compatibility, Mix+Hex always uses particular hex_core and so does rebar3_hex (it wasn't always the case, initially it was not pinning) so it's OK to have some breakage before v1.0.

**Comment by paulo-ferraz-oliveira** [comment]
👋 @wojtekmach. I didn't see there was an issue here already. I can update the other pr (`hex_core`) to only consider binaries (in which case the spec is a bit less strict, but that seems acceptable; I can add the accepted keys as a comment, in that case). Thanks for the feedback.

**Comment by wojtekmach** [comment]
@paulo-ferraz-oliveira actually, let's move the conversation to #71 and close this in favour of thereof?

I re-read the issue and I think the consensus was we should keep the atom keys because we can type spec them however we dump them to binaries before sending to the server. I would not, however, allow passing a map of either or both atom and binary keys, we need to settle one way or another.
