### ISSUE TITLE
Run tests on OTP 17

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex_core#35]
There's a regression on master that was only caught when I tried vendoring master into Hex. proper plugin does not compile on otp 17, so we need to again try fixing that or add some workaround.

**Comment by ferd** [comment]
have you tried making it a project plugin so it does not get installed as a dep?

**Comment by wojtekmach** [comment]
@ferd yes, no cigar. Even if I, as a hack, try moving proper to separate rebar profile (so it's not even installed by default) I'm still getting failures when running `rebar3 eunit` because it can't find `proper.hrl` - https://github.com/hexpm/hex_core/blob/master/test/prop_hex_tarball.erl#L2.

https://github.com/ferd/rebar3_proper/issues/24

**Comment by wojtekmach** [comment]
Fixed on master by updating to proper 1.3.
