### ISSUE TITLE
Quoting etag required

### ISSUE THREAD

**Issue by tsloughter** [hexpm/hex_core#43]
I noticed our caching wasn't working and discovered the need to do the quoting of the etag when building the hex core config map:

```
#{http_etag => <<"\"", ETag/binary, "\"">>},
```

I can send a patch if you're ok with this being done `hex_http` instead, but does it need to check and not add extra quotes or can it just assume the user will not send a quoted etag?

**Comment by wojtekmach** [comment]
I believe our servers always return etags in quotes (as per spec) and so the client receiving the etag from response headers should pass it along unchanged; however if we returned it unquoted it's a bug.

**Comment by tsloughter** [comment]
Ah, yup, I see we are stripping it before writing it to a file :). Not sure why it is stripping, going to try just removing that in rebar3. Thanks!
