### ISSUE TITLE
Check rebar vs rebar3 when guessing build tools

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex_core#44]
https://github.com/hexpm/hex_core/blob/v0.2.0/src/hex_tarball.erl#L9:L15

We used to differentiate between rebar and rebar3 and we may still do on the server, so this needs double-checking.

**Comment by ericmj** [comment]
I think we have always defaulted to rebar3 unless the user overrides. What is the best way to detect which version is being used?

**Comment by ferd** [comment]
there's no great way since we wanted to be mostly compatible with the old config format.
