### ISSUE TITLE
hex_api_package_owner requires api_key, but none is set... who's responsibility?

### ISSUE THREAD

**Issue by starbelly** [hexpm/hex_core#60]
This is really a question about responsibility. It's either the callers responsibility or hex_core's. If it's hex_core's responsibility then hex_core should set the api_key to read_key or write_key depending on the op. It's fine either way, but wanted to check before I sent up a PR.

**Comment by wojtekmach** [comment]
It's caller's responsibility to put the api_key into hex_core config map.

The api_key handling might differ between build tools. For example, Hex reads the api_key from following places:
- `HEX_API_KEY` env var
- ~/.hex/hex.config - read key is unencrypted, write key is always encrypted
- as of recent, we can even set project-specific Hex settings, so e.g. set `api_key` in `mix.exs`

By the time the api_key hits hex_core it must be unencrypted.

**Comment by starbelly** [comment]
Gotcha, makes sense 👍
