### ISSUE TITLE
Safe SSL defaults for built-in HTTP adapter

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex_core#62]
hex_core ships with a built-in httpc-based adapter but it's default options are insecure (doesn't verify server certs etc). See e.g.: https://blog.voltone.net/post/23 for more info.

We should port httpc configuration from Hex here or at the very least add some docs around this topic.

**Comment by essen** [comment]
Maybe you can just use this function when it is available: https://www.erlang.org/doc/apps/inets/httpc.html#ssl_verify_host_options/1

OTP-25.1+

**Comment by wojtekmach** [comment]
Good call, we can follow https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/inets when we detect we're running OTP 25 and maybe warn otherwise.

**Comment by essen** [comment]
Sounds good!
