### ISSUE TITLE
The built in httpc requests throw MatchErrors on connection loss

### ISSUE THREAD

**Issue by joladev** [hexpm/hex_core#68]
https://github.com/hexpm/hex_core/blob/master/src/hex_http_httpc.erl#L14

If your connection is gone the left hand side match fails because you actually get `{:error, {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}}`

It'd be nice if that error tuple was passed through instead of having to wrap all calls in `try` and rescuing the `MatchError`. I feel that the fact that it returns a ok tuple implies that it would also return an error tuple in this case

If this sounds reasonable I can make a PR

**Comment by wojtekmach** [comment]
Yup, PR sounds great. Good catch.

**Comment by ericmj** [comment]
Fixed in above PR.
