### ISSUE TITLE
This limit shouldn't be enforce by the library

### ISSUE THREAD

**Issue by isaacsanders** [hexpm/hex_core#91]
https://github.com/hexpm/hex_core/blob/a708f382f1b2e34b1d49adac18af8ce35c969af4/src/hex_tarball.erl

This is related to hexpm/hex#766.

This should be enforced by the repo implementation, not the core library.

**Comment by ericmj** [comment]
hex_core should enforce a default but it should be overridable by configuration.

**Comment by isaacsanders** [comment]
Closed by #93
